# Generated by Django 4.1.3 on 2022-11-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_user_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(related_name='owner', to='home.car'),
        ),
    ]
