# Generated by Django 4.1.3 on 2022-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_cars_user_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cars',
        ),
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(related_name='owner', to='home.car'),
        ),
    ]
