# Generated by Django 4.1.2 on 2022-11-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_user_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(related_name='owner', to='home.car'),
        ),
    ]
